dotfiles_dir = "dotfiles"

[settings]
hooks = ["sway reload"]
vars = [
    "bombadil/themes/sweay.toml",
    "bombadil/vars.toml",
]

[settings.dots]
alacritty = { source = "alacritty", target = ".config/alacritty" }
wofi = { source = "wofi", target = ".config/wofi" }
sway = { source = "sway", target = ".config/sway" }
waybar = { source = "waybar", target = ".config/waybar" }
swaynag = { source = "swaynag", target = ".config/swaynag" }  
## kanshi = { source = "kanshi", target = ".config/kanshi" }
mako = { source = "mako", target = ".config/mako" }
zsh = { source = "zsh/zshrc", target = ".zshrc" }
nvim = { source = "nvim", target = ".config/nvim" }
ncmpcpp = { source = "ncmpcpp", target = ".ncmpcpp" }
## mdp = { source = "mpd", target = ".config/mpd" }
## gtk2 = { source = "gtk/gtkrc-2.0", target = ".gtkrc-2.0" }
## gtk3 = { source = "gtk/gtk-3.0", target = ".config/gtk-3.0" }
neofetch = { source = "neofetch", target = ".config/neofetch" }

